env: home
ip: 192.168.56.15
iface: enp0s8
instance: lan
port: 8443
real_port: 6443
http_check: "GET /healthz"
http_status: 200
ssl: yes
backend_servers:
  - k8s-master01
  - k8s-master02
  - k8s-master03
