vhost_name: website

project_components:
- component: node
  primary_hostname: website
  hostname:
  - website2
  - website
  http_port: 8080
  https_port: 8443
  service_port: 3000
  service_protocol: http
  redirect_http: yes
  deploy_lb_vhost: yes
  lb_conf_name: mutualized-production
  auth: no
  allow_uploads: yes
  max_body_size: 20
  docker_image: '{{ node_docker_registry }}'
  docker_container: '{{ node_docker_container }}'
  volumes: '{{ node_volumes }}'

node_docker_container:
  count_per_host: 1
  cpus: 0.5
  memory: 128m
  uid: 10001
  gid: 0
  env: "{{ node_docker_env }}"

node_docker_registry:
  login: no
  name: "{{ component }}-{{ application }}"
  registry_url: registry:5000
  registry_login: test
  registry_password: test
  registry_email: 'sebastien.rohaut@gmail.com'
  registry_check: yes


node_docker_env:
  host: '{{ inventory_hostname }}'
  component: '{{ component }}'
  environment: '{{ env }}'
  application: '{{ application }}'
  release: '{{ release|default("0.0.0") }}'
  NODE_ENV: 'production'
  LOG_LEVEL: 'info'
  SERVICE_PORT: '3000'

node_volumes: 
- type: file
  local_path: /opt/ansible/build/roles/deploy_autodocker_image/files/website/file1
  dest_file: /opt/myfiles/file1
- type: file
  local_path: /opt/ansible/build/roles/deploy_autodocker_image/files/website/file2
  dest_file: /opt/myfiles/file2
- type: emptydir
  local_path: mydir1
  dest_path: /opt/mydir1
- type: nfs
  nfs_path: 192.168.56.2:/eni-todo-storage
  local_path: eni-todo-storage
  dest_path: /
