#
# prepare k8s server
#
#
- name : upgrade to latest packages
  ansible.builtin.apt: 
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags:
    - upgrade

- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes      
  tags:
    - upgrade

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  ansible.builtin.stat: 
    path: /var/run/reboot-required 
    get_checksum: no
  tags:
    - upgrade

- name: Reboot the Debian or Ubuntu server
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists
  tags:
    - upgrade

- name: Configure timezone
  community.general.timezone:
    name: "{{ timezone }}"
  tags:
    - time

- name: Set ntp server
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^(#|)NTP="
    line: "NTP={{ ntp }}"
  register: setntp
  tags:
    - time

- name: Disable/Reenable ntp
  ansible.builtin.shell: "timedatectl set-ntp {{ item }}"
  args:
    executable: /usr/bin/bash
  loop:
    - "off"
    - "on"
  when: setntp.changed
  tags:
    - time

- name: Create apt keyrings directory if needed
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755
    owner: root
    group: root
  tags:
    - repository

- name: Download k8s repository signing key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
    dest: /tmp/kubernetes-apt-keyring.key
    mode: 0644
    force: true
  tags:
    - repository

- name: Add k8s repository signing key
  ansible.builtin.shell: "cat /tmp/kubernetes-apt-keyring.key | gpg --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"
  changed_when: false
  tags:
    - repository

- name: Add machine architecure
  ansible.builtin.shell: "dpkg --print-architecture"
  register: architecture
  tags:
    - repository

- name: Get current ubuntu release
  ansible.builtin.shell: lsb_release -cs
  register: ubuntu_release
  tags:
    - repository

- name: Add k8s repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    filename: kubernetes
  tags:
    - repository

- name: Install necessary packages
  ansible.builtin.apt:
    pkg:
    - ufw
    - net-tools
    - apt-transport-https
    - curl
    - vim
    - git
    - wget
    - iputils-ping
    - kubelet
    - kubeadm
    - kubectl
    - gnupg-agent
    - software-properties-common
    - ca-certificates
    - containerd
    - nfs-kernel-server
    state: latest
    update_cache: yes
  tags:
    - packages

- name: Hold k8s packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  tags:
    - packages

- name: configure containerd etc directory (1/4)
  ansible.builtin.file:
    path: /etc/containerd
    state: "directory"
  tags:
    - containerd

- name: configure containerd default configuration (2/4)
  ansible.builtin.shell: "containerd config default>/etc/containerd/config.toml"
  args:
    executable: /usr/bin/bash
  tags:
    - containerd

- name: configure containerd to use systemd cgroups (3/4)
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(.*)SystemdCgroup'
    line: '\1SystemdCgroup = true'
    backrefs: yes
  tags:
    - containerd

- name: Enable containerd (4/4)
  ansible.builtin.systemd_service:
    enabled: yes
    state: restarted
    name: containerd
  tags:
    - containerd

- name: Get releases
  ansible.builtin.shell: kubectl version --client && kubeadm version
  args:
    executable: /usr/bin/bash
  register: k8s_releases

- name: Display
  debug:
    msg: "{{ k8s_releases.stdout }}"

- name: Disable SWAP in realtime (1/2)
  ansible.builtin.shell: swapoff -a
  args:
    executable: /usr/bin/bash
  tags:
    - swap

- name: Disable SWAP in fstab (2/2)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  tags:
    - swap

- name: Load modules if not done
  community.general.modprobe:
    name: "{{ item }}"
    persistent: present
  loop:
    - overlay
    - br_netfilter   
  tags:
    - modules


- name: Configure sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    reload: yes
  loop:
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
    - { name: "net.bridge.bridge-nf-call-iptables", value: 1 }
    - { name: "net.ipv4.ip_forward", value: 1 }
  tags:
    - sysctl

- name: configure UFW globally
  community.general.ufw:
    state: enabled
    rule: allow
    port: ssh
    proto: tcp
  tags:
    - firewall

- name: Configure ufw defaults
  community.general.ufw: 
    direction: "{{ item.direction }}" 
    policy: "{{ item.policy }}"
  loop:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
    - { direction: 'routed', policy: 'allow' }
  tags:
    - firewall

- name: Configure UFW Firewall for Masters
  community.general.ufw: 
    rule: allow
    from_ip: 192.168.56.0/24
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: 
    - { port: "6443", proto: "tcp" }
    - { port: "2379:2380", proto: "tcp" }
    - { port: "10250:10252", proto: "tcp" }
    - { port: "8285", proto: "udp" }
    - { port: "8472", proto: "udp" }
  when: inventory_hostname in groups['k8s_cplanes']
  tags:
    - firewall

- name: Configure UFW Firewall for Workers
  community.general.ufw: 
    rule: allow
    from_ip: 192.168.56.0/24
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: 
    - { port: "10250", proto: "tcp" }
    - { port: "8472", proto: "udp" }
    - { port: "30000:32767", proto: "tcp" }
    - { port: "30000:32767", proto: "udp" }
  when: inventory_hostname in groups['k8s_workers']
  tags:
    - firewall

- name: Additionnal Firewall urels for Infra workers nodes
  community.general.ufw: 
    rule: allow
    from_ip: 192.168.56.0/24
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: 
    - { port: "80", proto: "tcp" }
    - { port: "443", proto: "tcp" }
  when: inventory_hostname in groups['k8s_infra']
  tags:
    - firewall

- name: "Firewall for nginx ingress controller: masters must access 8443 port"
  community.general.ufw:
    rule: allow
    from_ip:  "{{ lookup('dig', '{{ item }}') }}"
    port: "8443"
    proto: "tcp"
  with_items: "{{ groups['k8s_cplanes'] }}"   
  when: inventory_hostname in groups['k8s_infra']
  tags:
    - firewall

- name: Allow trafic from 10.0.0.0/8 to anywhere (services, kube)
  community.general.ufw:
    rule: allow
    from: 10.0.0.0/8
    to: any
  tags:
    - firewall
 
- name: Enable kubelet
  ansible.builtin.systemd_service:
    enabled: yes
    name: kubelet
  tags:
    - kubelet

- name: disable apparmor
  ansible.builtin.systemd_service:
    enabled: no
    state: stopped
    name: apparmor
  tags:
    - kubelet
    - bad-security
