#
# prepare k8s server
#
#
- name : upgrade to latest packages
  apt: 
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags:
    - upgrade

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes      
  tags:
    - upgrade

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  stat: 
    path: /var/run/reboot-required 
    get_checksum: no
  tags:
    - upgrade

- name: Reboot the Debian or Ubuntu server
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists
  tags:
    - upgrade

- name: Configure timezone
  timezone:
    name: "{{ timezone }}"
  tags:
    - time

- name: Set ntp server
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^(#|)NTP="
    line: "NTP={{ ntp }}"
  register: setntp
  tags:
    - time

- name: Disable/Reenable ntp
  shell: "timedatectl set-ntp {{ item }}"
  args:
    executable: /usr/bin/bash
  loop:
    - "off"
    - "on"
  when: setntp.changed
  tags:
    - time
