---
- name: "install registry"
  hosts: registry
  become: yes
  #vars:
  

  pre_tasks:
    - shell: echo 'starting install'
  
  # this double use of doker roles is a hack for the certicat, improve separate roles
  roles:
    - { role: docker   }
    - { role: registry }
    - { role: docker   }

  tasks:
    - shell: echo 'roles done'

  post_tasks:
    - shell: echo 'Install done'
