---
- name: "Prerequires for k8s masters and workers"
  become: yes
  become_user: root
  hosts: k8s
  # serial: 1
  vars:
    - base_dir: "/opt/data"
  vars_files:
    - "vars/default.yml"
  pre_tasks:
    - shell: echo 'starting install'
  roles:
    - { role: prepare_k8s_server }
  tasks:
    - shell: echo 'roles done'
  post_tasks:
    - shell: echo 'install done'
