---
- name: "Prerequires for nfsha servers"
  become: yes
  become_user: root
  hosts: nfsha
  # we set those operation one server at a time
  vars:
    - base_dir: "/opt/data"
    - update_cache: "false"
  vars_files:
    - "vars/default.yml"
  pre_tasks:
    - shell: echo 'starting install'
  roles:
    - { role: setup_nfsha_sample }
  tasks:
    - shell: echo 'roles done'
  post_tasks:
    - shell: echo 'install done'

